github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

tasks:
  - init: pip3 install -r requirements.txt

vscode:
  extensions:
    - code --install-extension aaron-bond.better-comments
    - CoenraadS.bracket-pair-colorizer-2
    - donjayamanne.githistory
    - dracula-theme.theme-dracula
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - GitHub.copilot
    - GitHub.vscode-pull-request-github
    - James-Yu.latex-workshop
    - magicstack.MagicPython
    - mechatroner.rainbow-csv
    - mhutchie.git-graph
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - naumovs.color-highlight
    - oderwat.indent-rainbow
    - PKief.material-icon-theme
    - TabNine.tabnine-vscode
    - VisualStudioExptTeam.vscodeintellicode
    - wayou.vscode-todo-highlight
    - zhuangtongfa.material-theme